-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 11:33:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tpi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tpi` ;

-- -----------------------------------------------------
-- Schema tpi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpi` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `tpi` ;

-- -----------------------------------------------------
-- Table `tpi`.`Trips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpi`.`Trips` ;

CREATE TABLE IF NOT EXISTS `tpi`.`Trips` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `destination` VARCHAR(60) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `description` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueTrip` (`destination` ASC, `startdate` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi`.`Activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpi`.`Activities` ;

CREATE TABLE IF NOT EXISTS `tpi`.`Activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `date` DATE NOT NULL,
  `trip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueActivity` (`name` ASC, `date` ASC) VISIBLE,
  INDEX `fk_Activities_Trips1_idx` (`trip_id` ASC) VISIBLE,
  CONSTRAINT `fk_Activities_Trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `tpi`.`Trips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi`.`Accommodation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpi`.`Accommodation` ;

CREATE TABLE IF NOT EXISTS `tpi`.`Accommodation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `trip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueAccommodation` (`address` ASC, `startdate` ASC) VISIBLE,
  INDEX `fk_Accommodation_Trips1_idx` (`trip_id` ASC) VISIBLE,
  CONSTRAINT `fk_Accommodation_Trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `tpi`.`Trips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpi`.`Users` ;

CREATE TABLE IF NOT EXISTS `tpi`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstconnexion` TINYINT NULL,
  `teacher` TINYINT NOT NULL,
  `Trips_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUser` (`email` ASC) INVISIBLE,
  INDEX `fk_Users_Trips1_idx` (`Trips_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Trips1`
    FOREIGN KEY (`Trips_id`)
    REFERENCES `tpi`.`Trips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
