-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 11:19:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Trips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Trips` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Trips` (
  `idTrips` INT NOT NULL AUTO_INCREMENT,
  `destination` VARCHAR(60) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `description` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idTrips`),
  UNIQUE INDEX `UniqueTrip` (`destination` ASC, `startdate` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `idStudents` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstconnexion` TINYINT NOT NULL,
  `Trips_idTrips` INT NOT NULL,
  PRIMARY KEY (`idStudents`),
  UNIQUE INDEX `UniqueStudent` (`email` ASC) INVISIBLE,
  INDEX `fk_Students_Trips_idx` (`Trips_idTrips` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Trips`
    FOREIGN KEY (`Trips_idTrips`)
    REFERENCES `mydb`.`Trips` (`idTrips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teachers` (
  `idTeachers` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Trips_idTrips` INT NOT NULL,
  PRIMARY KEY (`idTeachers`),
  UNIQUE INDEX `UniqueTeacher` (`email` ASC) VISIBLE,
  INDEX `fk_Teachers_Trips1_idx` (`Trips_idTrips` ASC) VISIBLE,
  CONSTRAINT `fk_Teachers_Trips1`
    FOREIGN KEY (`Trips_idTrips`)
    REFERENCES `mydb`.`Trips` (`idTrips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Activities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Activities` (
  `idActivities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `date` DATE NOT NULL,
  `Trips_idTrips` INT NOT NULL,
  PRIMARY KEY (`idActivities`),
  UNIQUE INDEX `UniqueActivity` (`name` ASC, `date` ASC) VISIBLE,
  INDEX `fk_Activities_Trips1_idx` (`Trips_idTrips` ASC) VISIBLE,
  CONSTRAINT `fk_Activities_Trips1`
    FOREIGN KEY (`Trips_idTrips`)
    REFERENCES `mydb`.`Trips` (`idTrips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accommodation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Accommodation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Accommodation` (
  `idAccommodation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `Trips_idTrips` INT NOT NULL,
  PRIMARY KEY (`idAccommodation`),
  UNIQUE INDEX `UniqueAccommodation` (`address` ASC, `startdate` ASC) VISIBLE,
  INDEX `fk_Accommodation_Trips1_idx` (`Trips_idTrips` ASC) VISIBLE,
  CONSTRAINT `fk_Accommodation_Trips1`
    FOREIGN KEY (`Trips_idTrips`)
    REFERENCES `mydb`.`Trips` (`idTrips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
tpi